export const bioCopy = {
  highlight: "Tyler Hartley began harp lessons at the age of six",
  paragraphOne: "with Atlanta Opera harpist Susan Bennett Brady. Throughout middle school and high school, Tyler pursued a variety of performance experiences including 12 years in the Atlanta Harp Ensemble and four years with the prestigious Atlanta Symphony Youth Orchestra. She began her collegiate studies at the Eastman School of Music, where she was a recipient of the Eileen Malone Scholarship and studied under Kathleen Bride, and later attended Kennesaw State University, where she was 2011’s Concerto Competition winner with the Boieldieu Harp Concerto and studied under Elisabeth Remy Johnson of the Atlanta Symphony Orchestra. Tyler has performed in master classes with renowned harpists Judy Loman, Alice Giles, Kimberly Rowe, Catrin Finch, Bridget Kibbey, Elaine Barber, and Maria Luisa Rayan-Forero. Tyler has attended Eastern Music Festival, Saratoga Harp Colony, Miami Summer Music Festival, and Round Top Festival and has spent several summers at the Young Artist's Harp Seminar, first as a student and later as a theory instructor and counselor.",
  paragraphTwo: "An avid performer and orchestra lover, Tyler serves as principal harpist for the Gwinnett Ballet Theatre Orchestra, principal harpist for the Georgia Philharmonic Orchestra and second harpist for the Georgia Symphony Orchestra. In addition,she frequently freelances with various regional orchestras, wind ensembles, and choral groups including the Columbus Symphony Orchestra, Valdosta Symphony Orchestra, Macon Symphony Orchestra, Jacksonville Symphony Orchestra, Atlanta Philharmonic Orchestra, North Georgia Symphony Orchestra, South Florida Symphony Orchestra, Athens Choral Society, Voices of North Georgia, Tara Winds, Atlanta Freedom Band, Coastal Symphony of Georgia, and the Atlanta Wind Symphony.",
  paragraphThree: "Tyler is also a top-rated musician on the gig and wedding scene, offering an extensive and eclectic playlist of music that includes both solo and harp-and-violin duo offerings.",
  paragraphFour: "Tyler teaches private lessons on both lever and pedal harp to students of all ages from her home in Woodstock and her satellite studio in Roswell. Her students have been accepted into Georgia Symphony Youth Orchestra, Metropolitan Youth Symphony Orchestra, Georgia Piedmont Youth Symphony, Alpharetta Youth Symphony Orchestra, All-State Orchestra, Summer Harp Academy, Young Artist’s Harp Seminar, and the Peabody Institute of Music.",
  paragraphFive: "Tyler is currently serving her second term as Secretary of the Georgia Chapter of the American Harp Society.  In her spare time, Tyler enjoys playing card, board, and video games, snuggling with her lab-mutt Jojo, and getting personally invested in TV series. She has watched The Office to completion six times.",
  cta: "Contact Tyler for more information about event booking or private lessons at HarpistTyler@gmail.com"
}
